config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "topics#index"

  resources :topics do
    resources :comments # NHO: you have multiple routes going to the same controller actions, might want to limit the routes made here
  end

  resources :comments, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  # NHO: probably want to modify this relationship by adding a depedent: :destroy method call
  # to prevent orphaned comment records
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # NHO: can you see a line this is repetitive in this controller?
  # We can help DRY up this controller by using before_action methods to do common tasks such as
  # find a topic

  # NHO: this method is not consistent with the route,
  # I dont think this is being used 
  def index
    @comments = Comment.all
  end

  def show
    @topic = Topic.find params[:topic_id]
    @comment = Comment.find params[:id]
  end

  def new
    @comment = Comment.new
  end

  def create
    @topic = Topic.find(params[:comment][:topic_id])
    @comment = @topic.comments.create(comment_params.merge(user: current_user))
    redirect_to topic_path(@topic)
 end

  def edit
    @topic = Topic.find params[:topic_id]
    @comment = Comment.find params[:id]
  end

  def update
    @topic = Topic.find params[:topic_id]
    # NHO: @comment = Comment.find(params[:id]) ?
    @comment = Comment.where(topic: @topic.id)[0] # NHO: is this always the first? Can a user have more than one comment?
    @comment.update(comment_params)
    if @comment.user == current_user # NHO: Nice auth!
      @comment.update(comment_params)
    else
      flash[:alert] = "Only the author of the comment can edit"
    end
    redirect_to topic_comment_path(@topic, @comment)
  end

  def destroy
    @topic = Topic.find params[:topic_id]
    @comment = Comment.find params[:id]
    # @comment = Comment.where(topic: @topic.id)[0]
    if @comment == nil
      redirect_to @topic and return
    else
      if @comment.user == current_user
        @comment.destroy
      else
        flash[:alert] = "Only the author of the comment can delete"
      end
    end
    redirect_to topic_path(@topic)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :topic)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # NHO: can you see a line this is repetitive in this controller?
  # We can help DRY up this controller by using before_action methods to do common tasks such as
  # find a topic
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find params[:id]
    @comment = @topic.comments
  end

  def edit
    @topic = Topic.find params[:id]
  end

  def new
    @comment = Comment.new
  end

  def create
    @topic = Topic.create!(topic_params)

    redirect_to topic_path(@topic)
  end

  def update
    @topic = Topic.find params[:id]
    @topic.update(topic_params)

    redirect_to topic_path(@topic)
  end

  def destroy
    @topic = Topic.find params[:id]
    @topic.destroy

    # NHO: this will cause undesired behavior because the topic has already been deleted
    # probably want to redirect_to topics_path
    redirect_to topic_path
  end

  private
  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/edit.html.erb
<div class="comment">
  <div class="issue">
    <h2>Edit</h2>

      <%= form_for [@topic, @comment] do |f| %>

        <%= f.label :"Choose an Issue which most closely pertains to your comment:" %>
        <br>
        <%= f.collection_select :topic_id, Topic.all, :id, :name %>
        <br>

        <%= f.label :"Let your local Member of Congress know how you feel:" %>
        <%= f.text_area :body %>

        <%= f.submit "Edit Comment" %>

      <% end %>
  </div>
</div>

app/views/comments/index.html.erb
<!-- NHO: reminder to delete unused views  -->

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>

<% end %>

app/views/comments/show.html.erb
<div class="comment">
  <div class="issue">
    <h2>Submit a Comment on an Issue</h2>

    <%= @comment.body %>

    <p>Sucessfully Updated!!</p>

    <%= link_to "Return to Comments", topic_path(@topic) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fireside2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/topics/edit.html.erb
<h1>Harambe will never be changed</h1>

app/views/topics/index.html.erb
<div class="fire">
  <!-- NHO: should this header be in the application.html.erb so its on every page?  -->
  <header>
    <% if !current_user %>
    <section class="login">
      <%= button_to "Sign Up", new_user_registration_path %>
      <%= button_to "Sign In", new_user_session_path %>
    <% else %>
    <section class="logout">
    <a href="/topics/new">Comment on a Topic</a>
      <%= button_to "Sign Out", destroy_user_session_path, :method => :delete %>
        <%= current_user.email  %>
    <% end %>
    </section>
  </header>
  <div class="front">
    <h1>F i r e s i d e</h1>
    <h2>Chat with your Member of Congress</h2>
  </div>
</div>

app/views/topics/new.html.erb
<div class="comment">
  <h2>New Comment on an Issue</h2>

  <%= form_for @comment do |f| %>
    <div class="issue">
      <%= f.label :"Choose an Issue which most closely pertains to your comment:" %>
      <br>
      <%= f.collection_select :topic_id, Topic.all, :id, :name %>
    <%= f.label :"Let your local Member of Congress know how you feel:" %>
    <br>
    <%= f.text_area :body %>
    <br>
    <%= f.submit "Create Comment" %>
  <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="comment">
  <div class="issue">
    <h2>Submit a Comment on an Issue</h2>

    <table>
      <tr>
        <th>Body</th>
        <th>Options</th>
      </tr>

      <% @topic.comments.each do |comment|%>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to "Edit", edit_topic_comment_path(@topic, comment) %></td>
        <td><%= link_to "Delete", topic_comment_path(@topic, comment), method: :delete %></td>
      </tr>
      <% end %>
    </table>

    <%= @topic.name %>

    <button><a href="/">Return Home</a></button>
    <button><a href="/topics/new">Create New Topic</a></button>

  </div>
</div>